### ISSUE TITLE
CW_License_Menu

### ISSUE THREAD

**Issue by IndeedMiners** [OS-IT-Programming/cryptowoo-monero-addon#1]
Fatal error: Class 'CW_License_Menu' not found in /data/web/virtuals/182519/virtual/www/wp-content/plugins/cryptowoo-monero-addon-master/cryptowoo-monero-addon.php on line 34

Same error is also with Verctoin addon when I download it master branch and not from release.

**Comment by Olsm** [comment]
I apologize for the late answer.

This addon is not yet finished.
As you can see there is no release yet.
It is a work in progress that will finish soon.

You will need a license from cryptowoo.
You will be able to get that from the website.

Thanks for your patience.
